In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd /content/drive/MyDrive/tcb
!ls

/content/drive/MyDrive/tcb
data.csv  linear.ipynb


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv('data.csv')

In [ ]:
data

Movie Release Date  Critic 1  Critic 2  \
0                              Iron Man     2-May-08       4.0       4.0   
1                   The Incredible Hulk    13-Jun-08       NaN       NaN   
2                            Iron Man 2     7-May-10       3.0       6.0   
3                                  Thor     6-May-11       4.0       6.0   
4    Captain America: The First Avenger    22-Jul-11       5.0       5.0   
5                 Marvel's The Avengers     4-May-12       3.0       8.0   
6                            Iron Man 3     3-May-13       3.0       NaN   
7                  Thor: The Dark World     8-Nov-13       3.0       3.0   
8   Captain America: The Winter Soldier     4-Apr-14       7.0       7.0   
9               Guardians of the Galaxy     1-Aug-14       5.0       6.0   
10              Avengers: Age of Ultron     1-May-15       NaN       4.0   
11                              Ant-Man    17-Jul-15       3.0       5.0   
12           Captain America: Civil War     6-May-16       7.0       NaN   
13                       Doctor Strange     4-Nov-16       4.0       6.0   
14       Guardians of the Galaxy Vol. 2     5-May-17       7.0      10.0   
15               Spider-Man: Homecoming     7-Jul-17       NaN       9.0   
16                       Thor: Ragnarok     3-Nov-17       NaN      10.0   
17                        Black Panther    16-Feb-18       NaN       7.0   
18               Avengers: Infinity War    27-Apr-18       7.0       7.0   
19                 Ant-Man and the Wasp     6-Jul-18       NaN       8.0   
20                       Captain Marvel     8-Mar-19       5.0       NaN   
21                    Avengers: Endgame    26-Apr-19       6.0       9.0   

    Critic 3  Critic 4  Critic 5  Audience Rating  
0        7.0       6.0       5.0              9.1  
1        6.0       3.0       5.0              7.0  
2        8.0       6.0       5.0              7.1  
3        8.0       5.0       NaN              7.6  
4        NaN       7.0       7.0              7.5  
5        8.0       NaN       9.0              9.1  
6        8.0       NaN       5.0              7.8  
7        9.0       5.0       5.0              7.5  
8        9.0       9.0       NaN              9.2  
9        NaN       9.0       8.0              9.2  
10       7.0       NaN       NaN              8.3  
11       6.0       NaN       4.0              8.5  
12       8.0       9.0       NaN              8.9  
13       8.0       NaN       5.0              8.6  
14       7.0       5.0      10.0              8.7  
15       NaN       8.0       8.0              8.7  
16       5.0       9.0       NaN              8.7  
17       6.0       6.0       8.0              7.9  
18       9.0       8.0       9.0              9.1  
19       6.0       7.0       NaN              8.1  
20       9.0       5.0       NaN              4.5  
21      10.0      10.0      10.0              9.0

In [ ]:
data.describe()

Critic 1   Critic 2   Critic 3   Critic 4   Critic 5  Audience Rating
count  16.000000  18.000000  19.000000  17.000000  15.000000        22.000000
mean    4.750000   6.666667   7.578947   6.882353   6.866667         8.186364
std     1.612452   2.057983   1.346427   1.964763   2.099887         1.080254
min     3.000000   3.000000   5.000000   3.000000   4.000000         4.500000
25%     3.000000   5.250000   6.500000   5.000000   5.000000         7.650000
50%     4.500000   6.500000   8.000000   7.000000   7.000000         8.550000
75%     6.250000   8.000000   8.500000   9.000000   8.500000         8.975000
max     7.000000  10.000000  10.000000  10.000000  10.000000         9.200000

In [ ]:
# Drop cột ko liên quan
data = data.drop(columns = ['Movie', 'Release Date'])

In [ ]:
train, test = train_test_split(data, test_size = 0.2, random_state = 42)

In [ ]:
for column in train.columns:
    col_mode = train[column].mean()
    train[column].fillna(col_mode, inplace = True)

for column in test.columns:
    col_mode = test[column].mean()
    test[column].fillna(col_mode, inplace = True)

In [ ]:
train

Critic 1   Critic 2  Critic 3  Critic 4   Critic 5  Audience Rating
5   3.000000   8.000000       8.0       7.0   9.000000              9.1
20  5.000000   6.714286       9.0       5.0   7.272727              4.5
11  3.000000   5.000000       6.0       7.0   4.000000              8.5
3   4.000000   6.000000       8.0       5.0   7.272727              7.6
4   5.000000   5.000000       7.6       7.0   7.000000              7.5
17  4.692308   7.000000       6.0       6.0   8.000000              7.9
12  7.000000   6.714286       8.0       9.0   7.272727              8.9
18  7.000000   7.000000       9.0       8.0   9.000000              9.1
16  4.692308  10.000000       5.0       9.0   7.272727              8.7
2   3.000000   6.000000       8.0       6.0   5.000000              7.1
9   5.000000   6.000000       7.6       9.0   8.000000              9.2
21  6.000000   9.000000      10.0      10.0  10.000000              9.0
7   3.000000   3.000000       9.0       5.0   5.000000              7.5
10  4.692308   4.000000       7.0       7.0   7.272727              8.3
14  7.000000  10.000000       7.0       5.0  10.000000              8.7
19  4.692308   8.000000       6.0       7.0   7.272727              8.1
6   3.000000   6.714286       8.0       7.0   5.000000              7.8

In [ ]:
test

Critic 1  Critic 2  Critic 3  Critic 4  Critic 5  Audience Rating
0        4.0       4.0       7.0       6.0      5.00              9.1
13       4.0       6.0       8.0       6.5      5.00              8.6
8        7.0       7.0       9.0       9.0      5.75              9.2
1        5.0       6.5       6.0       3.0      5.00              7.0
15       5.0       9.0       7.5       8.0      8.00              8.7

In [ ]:
liner = LinearRegression()
# Tạo df mới(ko có cột target)
x_train_new = train.drop(columns = ['Audience Rating']).to_numpy()
x_test_new = test.drop(columns = ['Audience Rating']).to_numpy()
y_train_new = train['Audience Rating'].to_numpy()
y_test_new = test['Audience Rating'].to_numpy()

In [ ]:
x_train_new


array([[ 3.        ,  8.        ,  8.        ,  7.        ,  9.        ],
       [ 5.        ,  6.71428571,  9.        ,  5.        ,  7.27272727],
       [ 3.        ,  5.        ,  6.        ,  7.        ,  4.        ],
       [ 4.        ,  6.        ,  8.        ,  5.        ,  7.27272727],
       [ 5.        ,  5.        ,  7.6       ,  7.        ,  7.        ],
       [ 4.69230769,  7.        ,  6.        ,  6.        ,  8.        ],
       [ 7.        ,  6.71428571,  8.        ,  9.        ,  7.27272727],
       [ 7.        ,  7.        ,  9.        ,  8.        ,  9.        ],
       [ 4.69230769, 10.        ,  5.        ,  9.        ,  7.27272727],
       [ 3.        ,  6.        ,  8.        ,  6.        ,  5.        ],
       [ 5.        ,  6.        ,  7.6       ,  9.        ,  8.        ],
       [ 6.        ,  9.        , 10.        , 10.        , 10.        ],
       [ 3.        ,  3.        ,  9.        ,  5.        ,  5.        ],
       [ 4.69230769,  4.        ,  7. 

In [ ]:
y_train_new

array([9.1, 4.5, 8.5, 7.6, 7.5, 7.9, 8.9, 9.1, 8.7, 7.1, 9.2, 9. , 7.5,
       8.3, 8.7, 8.1, 7.8])

In [ ]:
x_test_new

array([[4.  , 4.  , 7.  , 6.  , 5.  ],
       [4.  , 6.  , 8.  , 6.5 , 5.  ],
       [7.  , 7.  , 9.  , 9.  , 5.75],
       [5.  , 6.5 , 6.  , 3.  , 5.  ],
       [5.  , 9.  , 7.5 , 8.  , 8.  ]])

In [ ]:
y_test_new

array([9.1, 8.6, 9.2, 7. , 8.7])

In [ ]:
lr = LinearRegression().fit(x_train_new, y_train_new)

In [ ]:
lr.predict(x_test_new)

array([7.49709651, 7.17215629, 7.71973437, 5.96388943, 8.45860241])